#!/usr/bin/env python
import os
import sys

godot_cpp = os.environ['GODOT_CPP']
if godot_cpp == "":
    print("Environment for GODOT_CPP is not set!")
    Exit(2)

# debreldir = "../build/SentinelLib/Release/SentinelLib.lib"
# mymode = ARGUMENTS.get('target', 'template_debug')
# if mymode == 'template_debug':
#    debreldir = "../build/SentinelLib/Debug/SentinelLib.lib"

env = SConscript(godot_cpp + "/SConstruct")
# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

# tweak this if you want to use different folders, or more folders, to store your source code in.
if env["CXX"] == "g++":
    env.Append(CXXFLAGS="-fexceptions")

env.Append(CPPPATH=["src/", "../SentinelLib/"])
# env.Append(LIBS=[debreldir])
sources = [Glob("src/*.cpp"), Glob("../SentinelLib/*.cpp")]

library = env.SharedLibrary(
    "demo/bin/libgdsentinel{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
    source=sources
)

Default(library)
